#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Djangolang
//! Source: ../schema/openapi.json
//! Version: 1.0
//! Generated by `oas3-gen v0.22.2`
//!
//! No description provided

use crate::api_types::*;
use anyhow::Context;
use reqwest::{Client, Url};
#[allow(unused_imports)]
use reqwest::multipart::{Form, Part};
#[allow(unused_imports)]
use reqwest::header::HeaderValue;
use validator::Validate;
pub const BASE_URL: &str = "https://example.com/";
#[derive(Debug, Clone)]
pub struct DjangolangClient {
    pub client: Client,
    pub base_url: Url,
}
impl DjangolangClient {
    /// Create a client using the OpenAPI `servers[0]` URL.
    #[must_use]
    pub fn new() -> Self {
        Self {
            client: Client::builder().build().expect("client"),
            base_url: Url::parse(BASE_URL).expect("valid base url"),
        }
    }
    /// Create a client with a custom base URL.
    pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
        Ok(Self {
            client: Client::builder().build().context("building reqwest client")?,
            base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
        })
    }
    /// Create a client from an existing `reqwest::Client`.
    pub fn with_client(
        base_url: impl AsRef<str>,
        client: Client,
    ) -> anyhow::Result<Self> {
        let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
        Ok(Self { client, base_url: url })
    }
    ///GET /api/cameras
    pub async fn get_cameras(
        &self,
        request: GetCamerasRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.get(url);
        let response = req_builder.send().await?;
        let parsed = GetCamerasRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///POST /api/cameras
    pub async fn post_cameras(
        &self,
        request: PostCamerasRequest,
    ) -> anyhow::Result<PostCamerasResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostCamerasRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///GET /api/cameras/{primaryKey}
    pub async fn get_camera(
        &self,
        request: GetCameraRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.get(url);
        let response = req_builder.send().await?;
        let parsed = GetCameraRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///DELETE /api/cameras/{primaryKey}
    pub async fn delete_camera(
        &self,
        request: DeleteCameraRequest,
    ) -> anyhow::Result<DeleteVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.delete(url);
        let response = req_builder.send().await?;
        let parsed = DeleteCameraRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///PATCH /api/cameras/{primaryKey}
    pub async fn patch_camera(
        &self,
        request: PatchCameraRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.patch(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PatchCameraRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///POST /api/cameras/{primaryKey}/segment-producer-claim
    pub async fn post_cameras_segment_producer_claim(
        &self,
        request: PostCamerasSegmentProducerClaimRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostCamerasSegmentProducerClaimRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///POST /api/cameras/{primaryKey}/stream-producer-claim
    pub async fn post_cameras_stream_producer_claim(
        &self,
        request: PostCamerasStreamProducerClaimRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostCamerasStreamProducerClaimRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///GET /api/detections
    pub async fn get_detections(
        &self,
        request: GetDetectionsRequest,
    ) -> anyhow::Result<GetDetectionResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.get(url);
        let response = req_builder.send().await?;
        let parsed = GetDetectionsRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///POST /api/detections
    pub async fn post_detections(
        &self,
        request: PostDetectionsRequest,
    ) -> anyhow::Result<PostDetectionsResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostDetectionsRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///GET /api/detections/{primaryKey}
    pub async fn get_detection(
        &self,
        request: GetDetectionRequest,
    ) -> anyhow::Result<GetDetectionResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.get(url);
        let response = req_builder.send().await?;
        let parsed = GetDetectionRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///DELETE /api/detections/{primaryKey}
    pub async fn delete_detection(
        &self,
        request: DeleteDetectionRequest,
    ) -> anyhow::Result<DeleteVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.delete(url);
        let response = req_builder.send().await?;
        let parsed = DeleteDetectionRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///PATCH /api/detections/{primaryKey}
    pub async fn patch_detection(
        &self,
        request: PatchDetectionRequest,
    ) -> anyhow::Result<GetDetectionResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.patch(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PatchDetectionRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///POST /api/object-detector-claim-video
    pub async fn post_object_detector_claim_videos(
        &self,
        request: PostObjectDetectorClaimVideosRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostObjectDetectorClaimVideosRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///POST /api/object-tracker-claim-video
    pub async fn post_object_tracker_claim_videos(
        &self,
        request: PostObjectTrackerClaimVideosRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostObjectTrackerClaimVideosRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///POST /api/segment-producer-claim-camera
    pub async fn post_segment_producer_claim_cameras(
        &self,
        request: PostSegmentProducerClaimCamerasRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostSegmentProducerClaimCamerasRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///POST /api/stream-producer-claim-camera
    pub async fn post_stream_producer_claim_cameras(
        &self,
        request: PostStreamProducerClaimCamerasRequest,
    ) -> anyhow::Result<GetCameraResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostStreamProducerClaimCamerasRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///GET /api/videos
    pub async fn get_videos(
        &self,
        request: GetVideosRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.get(url);
        let response = req_builder.send().await?;
        let parsed = GetVideosRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///POST /api/videos
    pub async fn post_videos(
        &self,
        request: PostVideosRequest,
    ) -> anyhow::Result<PostVideosResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostVideosRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///GET /api/videos/{primaryKey}
    pub async fn get_video(
        &self,
        request: GetVideoRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.get(url);
        let response = req_builder.send().await?;
        let parsed = GetVideoRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///DELETE /api/videos/{primaryKey}
    pub async fn delete_video(
        &self,
        request: DeleteVideoRequest,
    ) -> anyhow::Result<DeleteVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let req_builder = self.client.delete(url);
        let response = req_builder.send().await?;
        let parsed = DeleteVideoRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///PATCH /api/videos/{primaryKey}
    pub async fn patch_video(
        &self,
        request: PatchVideoRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.patch(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PatchVideoRequest::parse_response(response).await?;
        Ok(parsed)
    }
    ///POST /api/videos/{primaryKey}/object-detector-claim
    pub async fn post_videos_object_detector_claim(
        &self,
        request: PostVideosObjectDetectorClaimRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostVideosObjectDetectorClaimRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
    ///POST /api/videos/{primaryKey}/object-tracker-claim
    pub async fn post_videos_object_tracker_claim(
        &self,
        request: PostVideosObjectTrackerClaimRequest,
    ) -> anyhow::Result<GetVideoResponse> {
        request.validate().context("parameter validation")?;
        let url = self
            .base_url
            .join(&request.render_path()?)
            .context("constructing request url")?;
        let mut req_builder = self.client.post(url);
        req_builder = req_builder.json(&request.body);
        let response = req_builder.send().await?;
        let parsed = PostVideosObjectTrackerClaimRequest::parse_response(response)
            .await?;
        Ok(parsed)
    }
}
