# coding: utf-8

# flake8: noqa
"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.camera import Camera
from openapi_client.models.claim_request import ClaimRequest
from openapi_client.models.detection import Detection
from openapi_client.models.detection_bounding_box_inner import DetectionBoundingBoxInner
from openapi_client.models.get_cameras200_response import GetCameras200Response
from openapi_client.models.get_cameras_default_response import GetCamerasDefaultResponse
from openapi_client.models.get_detections200_response import GetDetections200Response
from openapi_client.models.get_videos200_response import GetVideos200Response
from openapi_client.models.patch_claim_video_for_object_detector_default_response import PatchClaimVideoForObjectDetectorDefaultResponse
from openapi_client.models.vec2 import Vec2
from openapi_client.models.video import Video
