# coding: utf-8

# flake8: noqa
"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.array_of_vec2_inner import ArrayOfVec2Inner
from openapi_client.models.camera import Camera
from openapi_client.models.claim_request import ClaimRequest
from openapi_client.models.detection import Detection
from openapi_client.models.get_cameras_default_response import GetCamerasDefaultResponse
from openapi_client.models.response_with_generic_of_camera import ResponseWithGenericOfCamera
from openapi_client.models.response_with_generic_of_detection import ResponseWithGenericOfDetection
from openapi_client.models.response_with_generic_of_video import ResponseWithGenericOfVideo
from openapi_client.models.vec2 import Vec2
from openapi_client.models.video import Video
