# coding: utf-8

"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.video import Video
from typing import Optional, Set
from typing_extensions import Self

class ResponseWithGenericOfVideo(BaseModel):
    """
    ResponseWithGenericOfVideo
    """ # noqa: E501
    count: Optional[StrictInt] = None
    error: Optional[List[StrictStr]] = None
    limit: Optional[StrictInt] = None
    objects: Optional[List[Video]] = None
    offset: Optional[StrictInt] = None
    status: Optional[StrictInt] = None
    success: Optional[StrictBool] = None
    total_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["count", "error", "limit", "objects", "offset", "status", "success", "total_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseWithGenericOfVideo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in objects (list)
        _items = []
        if self.objects:
            for _item in self.objects:
                if _item:
                    _items.append(_item.to_dict())
            _dict['objects'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseWithGenericOfVideo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "error": obj.get("error"),
            "limit": obj.get("limit"),
            "objects": [Video.from_dict(_item) for _item in obj["objects"]] if obj.get("objects") is not None else None,
            "offset": obj.get("offset"),
            "status": obj.get("status"),
            "success": obj.get("success"),
            "total_count": obj.get("total_count")
        })
        return _obj


