# coding: utf-8

"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.detection_api import DetectionApi


class TestDetectionApi(unittest.TestCase):
    """DetectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DetectionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_detection(self) -> None:
        """Test case for delete_detection"""
        pass

    def test_get_detection(self) -> None:
        """Test case for get_detection"""
        pass

    def test_get_detections(self) -> None:
        """Test case for get_detections"""
        pass

    def test_patch_detection(self) -> None:
        """Test case for patch_detection"""
        pass

    def test_post_detections(self) -> None:
        """Test case for post_detections"""
        pass

    def test_put_detection(self) -> None:
        """Test case for put_detection"""
        pass


if __name__ == "__main__":
    unittest.main()
