# coding: utf-8

"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.video_api import VideoApi


class TestVideoApi(unittest.TestCase):
    """VideoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VideoApi()

    def tearDown(self) -> None:
        pass

    def test_delete_video(self) -> None:
        """Test case for delete_video"""
        pass

    def test_get_video(self) -> None:
        """Test case for get_video"""
        pass

    def test_get_videos(self) -> None:
        """Test case for get_videos"""
        pass

    def test_patch_video(self) -> None:
        """Test case for patch_video"""
        pass

    def test_post_videos(self) -> None:
        """Test case for post_videos"""
        pass

    def test_put_video(self) -> None:
        """Test case for put_video"""
        pass


if __name__ == "__main__":
    unittest.main()
