/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the VideoObjectTrackerClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoObjectTrackerClaimRequest{}

// VideoObjectTrackerClaimRequest struct for VideoObjectTrackerClaimRequest
type VideoObjectTrackerClaimRequest struct {
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
	Until *time.Time `json:"until,omitempty"`
}

// NewVideoObjectTrackerClaimRequest instantiates a new VideoObjectTrackerClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoObjectTrackerClaimRequest() *VideoObjectTrackerClaimRequest {
	this := VideoObjectTrackerClaimRequest{}
	return &this
}

// NewVideoObjectTrackerClaimRequestWithDefaults instantiates a new VideoObjectTrackerClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoObjectTrackerClaimRequestWithDefaults() *VideoObjectTrackerClaimRequest {
	this := VideoObjectTrackerClaimRequest{}
	return &this
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *VideoObjectTrackerClaimRequest) GetTimeoutSeconds() float64 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret float64
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoObjectTrackerClaimRequest) GetTimeoutSecondsOk() (*float64, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *VideoObjectTrackerClaimRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given float64 and assigns it to the TimeoutSeconds field.
func (o *VideoObjectTrackerClaimRequest) SetTimeoutSeconds(v float64) {
	o.TimeoutSeconds = &v
}

// GetUntil returns the Until field value if set, zero value otherwise.
func (o *VideoObjectTrackerClaimRequest) GetUntil() time.Time {
	if o == nil || IsNil(o.Until) {
		var ret time.Time
		return ret
	}
	return *o.Until
}

// GetUntilOk returns a tuple with the Until field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoObjectTrackerClaimRequest) GetUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Until) {
		return nil, false
	}
	return o.Until, true
}

// HasUntil returns a boolean if a field has been set.
func (o *VideoObjectTrackerClaimRequest) HasUntil() bool {
	if o != nil && !IsNil(o.Until) {
		return true
	}

	return false
}

// SetUntil gets a reference to the given time.Time and assigns it to the Until field.
func (o *VideoObjectTrackerClaimRequest) SetUntil(v time.Time) {
	o.Until = &v
}

func (o VideoObjectTrackerClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoObjectTrackerClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Until) {
		toSerialize["until"] = o.Until
	}
	return toSerialize, nil
}

type NullableVideoObjectTrackerClaimRequest struct {
	value *VideoObjectTrackerClaimRequest
	isSet bool
}

func (v NullableVideoObjectTrackerClaimRequest) Get() *VideoObjectTrackerClaimRequest {
	return v.value
}

func (v *NullableVideoObjectTrackerClaimRequest) Set(val *VideoObjectTrackerClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoObjectTrackerClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoObjectTrackerClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoObjectTrackerClaimRequest(val *VideoObjectTrackerClaimRequest) *NullableVideoObjectTrackerClaimRequest {
	return &NullableVideoObjectTrackerClaimRequest{value: val, isSet: true}
}

func (v NullableVideoObjectTrackerClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoObjectTrackerClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


