/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
	"time"
)

// checks if the CameraSegmentProducerClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CameraSegmentProducerClaimRequest{}

// CameraSegmentProducerClaimRequest struct for CameraSegmentProducerClaimRequest
type CameraSegmentProducerClaimRequest struct {
	TimeoutSeconds *float64 `json:"timeout_seconds,omitempty"`
	Until *time.Time `json:"until,omitempty"`
}

// NewCameraSegmentProducerClaimRequest instantiates a new CameraSegmentProducerClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCameraSegmentProducerClaimRequest() *CameraSegmentProducerClaimRequest {
	this := CameraSegmentProducerClaimRequest{}
	return &this
}

// NewCameraSegmentProducerClaimRequestWithDefaults instantiates a new CameraSegmentProducerClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCameraSegmentProducerClaimRequestWithDefaults() *CameraSegmentProducerClaimRequest {
	this := CameraSegmentProducerClaimRequest{}
	return &this
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *CameraSegmentProducerClaimRequest) GetTimeoutSeconds() float64 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret float64
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameraSegmentProducerClaimRequest) GetTimeoutSecondsOk() (*float64, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *CameraSegmentProducerClaimRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given float64 and assigns it to the TimeoutSeconds field.
func (o *CameraSegmentProducerClaimRequest) SetTimeoutSeconds(v float64) {
	o.TimeoutSeconds = &v
}

// GetUntil returns the Until field value if set, zero value otherwise.
func (o *CameraSegmentProducerClaimRequest) GetUntil() time.Time {
	if o == nil || IsNil(o.Until) {
		var ret time.Time
		return ret
	}
	return *o.Until
}

// GetUntilOk returns a tuple with the Until field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CameraSegmentProducerClaimRequest) GetUntilOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Until) {
		return nil, false
	}
	return o.Until, true
}

// HasUntil returns a boolean if a field has been set.
func (o *CameraSegmentProducerClaimRequest) HasUntil() bool {
	if o != nil && !IsNil(o.Until) {
		return true
	}

	return false
}

// SetUntil gets a reference to the given time.Time and assigns it to the Until field.
func (o *CameraSegmentProducerClaimRequest) SetUntil(v time.Time) {
	o.Until = &v
}

func (o CameraSegmentProducerClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CameraSegmentProducerClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Until) {
		toSerialize["until"] = o.Until
	}
	return toSerialize, nil
}

type NullableCameraSegmentProducerClaimRequest struct {
	value *CameraSegmentProducerClaimRequest
	isSet bool
}

func (v NullableCameraSegmentProducerClaimRequest) Get() *CameraSegmentProducerClaimRequest {
	return v.value
}

func (v *NullableCameraSegmentProducerClaimRequest) Set(val *CameraSegmentProducerClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCameraSegmentProducerClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCameraSegmentProducerClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCameraSegmentProducerClaimRequest(val *CameraSegmentProducerClaimRequest) *NullableCameraSegmentProducerClaimRequest {
	return &NullableCameraSegmentProducerClaimRequest{value: val, isSet: true}
}

func (v NullableCameraSegmentProducerClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCameraSegmentProducerClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


