/*
Djangolang

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_client

import (
	"encoding/json"
)

// checks if the Vec2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vec2{}

// Vec2 struct for Vec2
type Vec2 struct {
	X *float64 `json:"X,omitempty"`
	Y *float64 `json:"Y,omitempty"`
}

// NewVec2 instantiates a new Vec2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVec2() *Vec2 {
	this := Vec2{}
	return &this
}

// NewVec2WithDefaults instantiates a new Vec2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVec2WithDefaults() *Vec2 {
	this := Vec2{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise.
func (o *Vec2) GetX() float64 {
	if o == nil || IsNil(o.X) {
		var ret float64
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vec2) GetXOk() (*float64, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *Vec2) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given float64 and assigns it to the X field.
func (o *Vec2) SetX(v float64) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *Vec2) GetY() float64 {
	if o == nil || IsNil(o.Y) {
		var ret float64
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vec2) GetYOk() (*float64, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *Vec2) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given float64 and assigns it to the Y field.
func (o *Vec2) SetY(v float64) {
	o.Y = &v
}

func (o Vec2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vec2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.X) {
		toSerialize["X"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["Y"] = o.Y
	}
	return toSerialize, nil
}

type NullableVec2 struct {
	value *Vec2
	isSet bool
}

func (v NullableVec2) Get() *Vec2 {
	return v.value
}

func (v *NullableVec2) Set(val *Vec2) {
	v.value = val
	v.isSet = true
}

func (v NullableVec2) IsSet() bool {
	return v.isSet
}

func (v *NullableVec2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVec2(val *Vec2) *NullableVec2 {
	return &NullableVec2{value: val, isSet: true}
}

func (v NullableVec2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVec2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


