# coding: utf-8

"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.camera_api import CameraApi


class TestCameraApi(unittest.TestCase):
    """CameraApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CameraApi()

    def tearDown(self) -> None:
        pass

    def test_delete_camera(self) -> None:
        """Test case for delete_camera

        """
        pass

    def test_get_camera(self) -> None:
        """Test case for get_camera

        """
        pass

    def test_get_cameras(self) -> None:
        """Test case for get_cameras

        """
        pass

    def test_patch_camera(self) -> None:
        """Test case for patch_camera

        """
        pass

    def test_post_cameras(self) -> None:
        """Test case for post_cameras

        """
        pass

    def test_put_camera(self) -> None:
        """Test case for put_camera

        """
        pass


if __name__ == '__main__':
    unittest.main()
