# coding: utf-8

"""
    Djangolang

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patch_claim_video_for_object_detector_default_response import PatchClaimVideoForObjectDetectorDefaultResponse

class TestPatchClaimVideoForObjectDetectorDefaultResponse(unittest.TestCase):
    """PatchClaimVideoForObjectDetectorDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchClaimVideoForObjectDetectorDefaultResponse:
        """Test PatchClaimVideoForObjectDetectorDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchClaimVideoForObjectDetectorDefaultResponse`
        """
        model = PatchClaimVideoForObjectDetectorDefaultResponse()
        if include_optional:
            return PatchClaimVideoForObjectDetectorDefaultResponse(
                error = [
                    ''
                    ],
                status = 56,
                success = True
            )
        else:
            return PatchClaimVideoForObjectDetectorDefaultResponse(
                error = [
                    ''
                    ],
                status = 56,
                success = True,
        )
        """

    def testPatchClaimVideoForObjectDetectorDefaultResponse(self):
        """Test PatchClaimVideoForObjectDetectorDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
